language: swift
xcode_workspace: pizza-delivery/pizza-delivery.xcworkspace
xcode_scheme: pizza-delivery
osx_image: xcode10.2
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 8
podfile: pizza-deliver—É/Podfile